# Generated by Django 3.2.8 on 2021-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211113_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='images/no_photo.jpg', upload_to='images/course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='images/no_photo.jpg', upload_to='images/course_images/'),
        ),
    ]
