# Generated by Django 3.2.8 on 2021-11-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211113_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=5, max_digits=2),
        ),
    ]
