# Generated by Django 3.2.8 on 2021-11-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211110_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='courses.course'),
        ),
    ]
