# Generated by Django 3.2.8 on 2021-11-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(related_name='courses', to='courses.Category'),
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
