# Generated by Django 3.2.8 on 2021-11-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20211110_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='static/images/no_photo.jpg', upload_to='static/images/course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='static/images/no_photo.jpg', upload_to='static/images/course_images/'),
        ),
    ]
