# Generated by Django 3.2.8 on 2021-12-11 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_assignment_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('A', 'عالی'), ('B', 'خیلی خوب'), ('C', 'خوب'), ('D', 'نیاز به تلاش بیشتر')], max_length=18)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='courses.homework')),
            ],
        ),
    ]
