# Generated by Django 3.2.8 on 2021-12-18 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_auto_20211211_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='courses.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='grade',
            field=models.CharField(choices=[('عالی', 'A'), ('خیلی خوب', 'B'), ('خوب', 'C'), ('نیاز به تلاش بیشتر', 'D')], max_length=18),
        ),
    ]
