# Generated by Django 3.2.8 on 2021-12-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20211211_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='grade',
            field=models.CharField(choices=[('عالی', 'A'), ('خیلی خوب', 'B'), ('خوب', 'C'), ('نیاز به تلاش بیشتر', 'D')], max_length=18),
        ),
    ]
