# Generated by Django 3.2.8 on 2021-11-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_image'),
        ('courses', '0010_alter_session_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='slug',
        ),
        # migrations.AlterField(
        #     model_name='course',
        #     name='instructor',
        #     field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.instructor'),
        # ),
    ]
