# Generated by Django 3.2.8 on 2021-11-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_image'),
        ('courses', '0011_auto_20211111_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, default=18, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.instructor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
