# Generated by Django 3.2.8 on 2021-11-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20211112_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
