# Generated by Django 3.2.8 on 2021-11-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
