# Generated by Django 3.2.8 on 2021-11-12 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='day',
            field=models.IntegerField(blank=True, default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'فروردین'), ('2', 'اردیبهشت'), ('3', 'خرداد'), ('4', 'تیر'), ('5', 'مرداد'), ('6', 'شهریور'), ('7', 'مهر'), ('8', 'آبان'), ('9', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='week_day',
            field=models.CharField(blank=True, choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دو\u200cشنبه'), ('3', 'سه\u200cشنبه'), ('4', 'چها\u200cر\u200cشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], max_length=10),
        ),
    ]
