# Generated by Django 3.2.8 on 2021-12-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20211217_2027'),
        ('courses', '0014_assignment_date'),
    ]

    operations = [
    ]
