# Generated by Django 3.2.8 on 2021-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20211112_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(blank=True),
        ),
    ]
