# Generated by Django 3.2.8 on 2021-12-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_merge_0011_auto_20211217_2027_0014_assignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
