# Generated by Django 3.2.8 on 2021-12-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_feedback_grade'),
        ('courses', '0016_alter_discount_code'),
    ]

    operations = [
    ]
