# Generated by Django 3.2.8 on 2021-12-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_discount_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
