# Generated by Django 3.2.8 on 2021-11-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisite',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='rate_no',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
    ]
