# Generated by Django 3.2.8 on 2021-12-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_merge_20211224_0128'),
        ('courses', '0018_discount'),
    ]

    operations = [
    ]
