# Generated by Django 3.2.8 on 2021-12-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_favorite'),
        ('courses', '0019_merge_0017_merge_20211224_0128_0018_discount'),
    ]

    operations = [
    ]
