# Generated by Django 3.2.8 on 2022-01-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20211229_1906'),
        ('courses', '0017_merge_20211224_0128'),
        ('courses', '0019_favorite'),
    ]

    operations = [
    ]
