# Generated by Django 3.2.8 on 2022-01-12 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_merge_20220113_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=5, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
