# Generated by Django 3.2.8 on 2021-10-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=6)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
