# Generated by Django 3.2.8 on 2021-10-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='09129786543', max_length=11),
            preserve_default=False,
        ),
    ]
