# Generated by Django 3.2.8 on 2021-11-20 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkyRoom',
            fields=[
                ('skyroom_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='SkyRoom ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
