# Generated by Django 3.2.8 on 2021-11-28 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userskyroom'),
        ('accounts', '0012_remove_user_image'),
    ]

    operations = [
    ]
