# Generated by Django 3.2.8 on 2021-11-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_0011_userskyroom_0012_remove_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
