# Generated by Django 3.2.8 on 2022-01-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='rate',
        ),
    ]
