# Generated by Django 3.2.8 on 2022-01-13 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_instructor_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=5, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
