# Generated by Django 3.2.8 on 2021-11-11 11:29

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=images.models.image_file_path, verbose_name='profile image')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
