# Generated by Django 3.2.8 on 2021-11-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='myimage',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
