# Generated by Django 3.2.8 on 2021-11-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20211111_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
