# Generated by Django 3.2.8 on 2021-11-12 15:40

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_myimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.ImageField(null=True, upload_to=images.models.image_file_path, verbose_name='profile image'),
        ),
    ]
