# Generated by Django 3.2.8 on 2021-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_myimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/images/', verbose_name='profile image'),
        ),
    ]
